package com.woniu.pojo;
// Generated 2019-12-14 17:18:37 by Hibernate Tools 5.4.7.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private Role role;
	private String uname;
	private String upwd;
	private String uphoto;

	public User() {
	}

	public User(Role role, String uname, String upwd, String uphoto) {
		this.role = role;
		this.uname = uname;
		this.upwd = upwd;
		this.uphoto = uphoto;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public String getUphoto() {
		return this.uphoto;
	}

	public void setUphoto(String uphoto) {
		this.uphoto = uphoto;
	}

	@Override
	public String toString() {
		return "User [uid=" + uid + ", role=" + role + ", uname=" + uname + ", upwd=" + upwd + ", uphoto=" + uphoto
				+ "]";
	}
	
}
